#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
int a,b;
cout<<endl<<"Let's Program a simple calculator"<<endl;
cout<<endl<<"Enter the value of a: ";
cin>> a;
cout<<endl<<"Enter the value of b: ";
cin>> b;
cout<<endl<<"Addition of a&b is:"<<a+b;
cout<<endl<<"Subraction of a&b is:"<<a-b;
cout<<endl<<"Product of a&b is:"<<a*b;
cout<<endl<<"Division of a&b is:"<<a/b;
getch();
}